### ISSUE TITLE
Some Error while executing

### ISSUE THREAD

**Issue by razcads** [tahseenjamal/nse_holidays#1]
Hi
Thanks for this code. I just blindly tried this out. Didnt work. Error thrown is below. If you are still active, maybe you could take a look in free time. I didnt look to debug as i am not good with HTML parsing!
**Error Text follows**
```
Traceback (most recent call last):
  File ../_Bot.py", line 32, in <module>
    trading_day = trading_day()
  File "..\trial.py", line 2634, in trading_day
    data = get(url, headers=headers)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python27\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by tahseenjamal** [comment]
Old website of NSE has moved to www1
Also now requests are blocked by NSE so switched the code to selenium. Clone the new code. And before using, check README for new updates
